version: '3.7'
services:
  backend:
    container_name: api-express
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=${ENVIRONMENT}
        - PORT_API=${PORT_API}
    image: backend
    volumes:
      - ./:/app
    ports:
      - ${PORT_API}:${PORT_API}
