name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Install dependecies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy Medipreco
        run: |
          rsync -ahrvzKO \
            --delete-excluded --filter='P /.env' --exclude='/src' --exclude='/index.ts' --exclude='/.github' --exclude='/.git' --exclude='/.tsconfig.json' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}:/opt/medipreco
          ssh -f ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} node /opt/medipreco/build/index.js
